INSERT INTO tb_client (name, created_At) VALUES ('Angela Dourado', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Danilela Rocha', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Tatiane Leite', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Simone Martins', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Caroline Leite Andrade', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Carlos Miguel de Arruda', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Guilherme Motta de Mello', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Paloma Souza Silva', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Diana Andrade Luz', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Marcos Alburquerque de lima', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Miguel Christian Luz', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Pietro Ferrari', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Augusto De Oliveira Carvalho', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Edimilson Andrade da Silva', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Diego Lima De Oliveira', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Kelly Tavares da Silva', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Domingue Loyolla', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Frank Almeida Damasceno', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Beattiz Souza', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Clara Onivero Antonia', NOW());